version: '2017-09-20'
pipeline:
- id: build
  type: script
  commands:
  - desc: "ping"
    cmd: |
      id
      env
      mkdir -p output
      git gh-tag test
  - desc: "ping"
    cmd: |
      apt-get update
      apt-get dist-upgrade

