version: '2017-09-20'
pipeline:
- id: build
  type: script
  commands:
  - desc: "ping"
    cmd: |
      id
      env
      mkdir -p output
      echo "Hello"
      sleep 5
      echo "world"
      # ping google.com
