version: '2017-09-20'
pipeline:
- id: build
  type: script
  commands:
  - desc: "ping"
    cmd: |
      id
      env
      mkdir -p output
      echo "Hello" > output/output.txt
      pwd
      ls -la
      ls -la output
      cat output/output.txt
      # ping google.com
